---
- name: Install MariaDB package on Ubuntu
  hosts: file_servers
  become: true
  tasks:
    - name: Install MariaDB package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
      tags: 
        - db
        - mariadb
        - ubuntu
