---
- name: MongoDB Installation Playbook
  hosts: mongodb_servers
  tasks:
    - name: Ensure MongoDB is installed
      apt:
        name: mongodb-org
        state: present
      notify: Restart MongoDB  

  handlers:
    - name: Restart MongoDB
      service:
        name: mongod
        state: restarted

